version: "3.7"
services:
  web:
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      PORT: 8000
      ENV: development
      MONGODB_URL: mongodb://root:root@mongodb:27017/?authSource=admin
      DATABASE_NAME: internshipper-dev
      ENCRYPTION_KEY: yA-XozFoGJnjSVhfu-qRAuw-ZJw3igLjltLL5goCQVE=
    ports:
      - 8000:8000
    volumes:
      - ./server:/srv/app
    depends_on:
      - mongodb
    command:
      [
        "uvicorn",
        "server:app",
        "--reload",
        "--app-dir",
        "app",
        "--host",
        "0.0.0.0",
      ]

  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db

  nginx:
    build:
      context: .
    ports:
      - 4433:443
    depends_on:
      - web
    environment:
      BACKEND_HOST: web
    volumes:
      - ./client/dist:/srv/app/client/dist
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/dev.key:/etc/nginx/internshipper.io.key
      - ./docker/nginx/dev.crt:/etc/nginx/internshipper.io.crt

volumes:
  mongodb_data:
