version: "3.7"
services:
  server: &server
    build:
      context: ./server
    environment: &server_env
      ENV: development
      MONGODB_URL: mongodb://root:root@mongodb:27017/?authSource=admin
      INTERNSHIPPER_APP_URL: http://localhost:8000
      DATABASE_NAME: internshipper-dev
      ENCRYPTION_KEY: yA-XozFoGJnjSVhfu-qRAuw-ZJw3igLjltLL5goCQVE=
      RABBITMQ_URI: amqp://guest:guest@rabbitmq:5672/?heartbeat=2
    depends_on:
      - mongodb
      - rabbitmq

  web:
    <<: *server
    build:
      context: ./server
    environment:
      <<: *server_env
      PORT: 8000
    ports:
      - 8000:8000
    volumes:
      - ./server:/srv/app
    command: ["uvicorn", "app.server:app", "--reload", "--host", "0.0.0.0"]

  worker:
    <<: *server
    command: ["celery", "-A", "lib.tasks", "worker", "-B", "-l", "info"]

  mongodb:
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb_data:/data/db

  nginx:
    build:
      context: .
    ports:
      - 4433:443
    depends_on:
      - web
    volumes:
      - ./docker/nginx/dev.key:/etc/nginx/internshipper.io.key
      - ./docker/nginx/dev.crt:/etc/nginx/internshipper.io.crt

  rabbitmq:
    image: rabbitmq:3.7-management-alpine

volumes:
  mongodb_data:
