name: Client

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  build_and_deploy:
    name: Build and deploy client to s3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Install dependencies
        working-directory: ./client
        run: yarn install --frozen-lockfile --link-duplicates --silent
      - name: Run tests
        working-directory: ./client
        run: yarn run test
      - name: Run linter
        working-directory: ./client
        run: yarn run lint
      - name: Run build
        working-directory: ./client
        run: yarn run build
      - name: Deploy to s3
        working-directory: ./client
        if: github.ref == 'refs/heads/master' && github.event_name == 'push'
        run: aws s3 sync ./dist/ s3://internshipper-static --delete
