name: Provision

on:
  push:
    branches:
      - master

jobs:
  build_and_deploy:
    name: Build and deploy client to s3
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
      - name: Build static content
        working-directory: ./client
        run: yarn install --frozen-lockfile --link-duplicates --silent && yarn run build
      - name: Deploy static site to S3 bucket
        working-directory: ./client
        run: aws s3 sync ./dist/ s3://internshipper-static --delete
