name: Server deployment

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker-compose build test-server
      - name: Run test container
        run: docker-compose run test-server

  lint:
    name: Run linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build container
        run: docker-compose build lint-server
      - name: Run lint container
        run: docker-compose run lint-server

  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
      - name: Create deployment
        run: |
          aws deploy create-deployment \
            --file-exists-behavior OVERWRITE \
            --application-name internshipper \
            --deployment-group-name production-server \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}
